dist: trusty

sudo: false

language: bash

addons:
  apt:
    packages:
      - ghostscript
      - poppler-utils

before_install:
- cd .. && ./biblatex-abnt/tests/texlive.sh
- cd biblatex-abnt
- mkdir /tmp/texlive/texmf-local/tex/latex/biblatex-contrib
- ln -s `pwd` /tmp/texlive/texmf-local/tex/latex/biblatex-contrib/biblatex-abnt
- export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
- texhash
- gem update bundler
- bundle update

script:
- rake cucumber
- cd tests && ./test.sh

after_failure:
- cat NBR10520-2002.log
- cat NBR6023-2002.log
- cat tmp/aruba/texto.log
- cat tmp/aruba/texto.txt

