dist: trusty

sudo: required

language: bash

addons:
  apt:
    packages:
      - ghostscript

before_install:
- cd .. && ./biblatex-abnt/tests/texlive.sh
- cd biblatex-abnt
- mkdir /tmp/texlive/texmf-local/tex/latex/biblatex-contrib
- sudo ln -s `pwd` /tmp/texlive/texmf-local/tex/latex/biblatex-contrib/biblatex-abnt
- export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
- sudo env "PATH=$PATH" texhash

script:
- cd tests && ./test.sh

after_failure:
- cat NBR10520-2002.log
- cat NBR6023-2002.log

